set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ",tmux-256color:RGB"
set -g status on
set -g set-clipboard on
set -g mouse on

# Pane configurations.
# set -g pane-border-style 'fg=red'
# set -g pane-active-border-style 'fg=yellow'

# Clock mode.
# setw -g clock-mode-colour cyan

# Copy mode.
# setw -g mode-style 'fg=black bg=red bold'

# Statusbar.
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=cyan'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

set -g window-status-current-style 'fg=black bg=red'
set -g window-status-current-format ' #I #W #F '

set -g window-status-style 'fg=red bg=black'
set -g window-status-format ' #I #[fg=white]#W #[fg=cyan]#F '

# Messages.
set -g message-style 'fg=black bg=red bold'

# Navigation with vim-tmux-navigator.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
